 -- SQL INSERT statements for the 'play' table
-- Auto Generated from play_inserts.py script
BEGIN;
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Hamlet', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Macbeth', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Othello', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('King Lear', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Romeo and Juliet', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Julius Caesar', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Tempest', 'William Shakespeare', 'Romance', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Twelfth Night', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('As You Like It', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Much Ado About Nothing', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('A Midsummer Night''s Dream', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Merchant of Venice', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Henry V', 'William Shakespeare', 'History', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Richard III', 'William Shakespeare', 'History', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Antony and Cleopatra', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Coriolanus', 'William Shakespeare', 'Tragedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Cymbeline', 'William Shakespeare', 'Romance', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Winter''s Tale', 'William Shakespeare', 'Romance', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Pericles', 'William Shakespeare', 'Romance', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Measure for Measure', 'William Shakespeare', 'Problem Play', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Taming of the Shrew', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('All''s Well That Ends Well', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Love''s Labour''s Lost', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Comedy of Errors', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Two Gentlemen of Verona', 'William Shakespeare', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Death of a Salesman', 'Arthur Miller', 'Drama', 2);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Crucible', 'Arthur Miller', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('A Streetcar Named Desire', 'Tennessee Williams', 'Drama', 11);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Cat on a Hot Tin Roof', 'Tennessee Williams', 'Drama', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Glass Menagerie', 'Tennessee Williams', 'Drama', 7);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Waiting for Godot', 'Samuel Beckett', 'Absurdist', 2);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Endgame', 'Samuel Beckett', 'Absurdist', 1);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Importance of Being Earnest', 'Oscar Wilde', 'Comedy', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('An Ideal Husband', 'Oscar Wilde', 'Comedy', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('No Exit', 'Jean-Paul Sartre', 'Existential', 1);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Hedda Gabler', 'Henrik Ibsen', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('A Doll''s House', 'Henrik Ibsen', 'Drama', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Seagull', 'Anton Chekhov', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Uncle Vanya', 'Anton Chekhov', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Three Sisters', 'Anton Chekhov', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Cherry Orchard', 'Anton Chekhov', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Pygmalion', 'George Bernard Shaw', 'Comedy', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Saint Joan', 'George Bernard Shaw', 'Drama', 6);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Long Day''s Journey Into Night', 'Eugene O''Neill', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Iceman Cometh', 'Eugene O''Neill', 'Drama', 4);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Our Town', 'Thornton Wilder', 'Drama', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Skin of Our Teeth', 'Thornton Wilder', 'Drama', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Visit', 'Friedrich Dürrenmatt', 'Tragicomedy', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Balcony', 'Jean Genet', 'Drama', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Rosencrantz and Guildenstern Are Dead', 'Tom Stoppard', 'Comedy', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Arcadia', 'Tom Stoppard', 'Comedy', 2);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Angels in America: Millennium Approaches', 'Tony Kushner', 'Drama', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Angels in America: Perestroika', 'Tony Kushner', 'Drama', 5);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Topdog/Underdog', 'Suzan-Lori Parks', 'Drama', 2);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Fences', 'August Wilson', 'Drama', 2);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Ma Rainey''s Black Bottom', 'August Wilson', 'Drama', 2);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Piano Lesson', 'August Wilson', 'Drama', 2);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Doubt: A Parable', 'John Patrick Shanley', 'Drama', 1);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('The Ferryman', 'Jez Butterworth', 'Drama', 3);
INSERT INTO play (play_title, play_author, play_genre, play_num_acts) VALUES ('Jerusalem', 'Jez Butterworth', 'Drama', 3);
COMMIT;
