-- SQL INSERT statements for table `patron`
-- Auto Generated From CSV: csv/patron.csv

INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('1', 'Patron1', 'Surname1', 'patron1@example.com', '587-555-2001', '1 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('2', 'Patron2', 'Surname2', 'patron2@example.com', '587-555-2002', '2 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('3', 'Patron3', 'Surname3', 'patron3@example.com', '587-555-2003', '3 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('4', 'Patron4', 'Surname4', 'patron4@example.com', '587-555-2004', '4 Example Street, Calgary, AB', '1');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('5', 'Patron5', 'Surname5', 'patron5@example.com', '587-555-2005', '5 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('6', 'Patron6', 'Surname6', 'patron6@example.com', '587-555-2006', '6 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('7', 'Patron7', 'Surname7', 'patron7@example.com', '587-555-2007', '7 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('8', 'Patron8', 'Surname8', 'patron8@example.com', '587-555-2008', '8 Example Street, Calgary, AB', '1');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('9', 'Patron9', 'Surname9', 'patron9@example.com', '587-555-2009', '9 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('10', 'Patron10', 'Surname10', 'patron10@example.com', '587-555-2010', '10 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('11', 'Patron11', 'Surname11', 'patron11@example.com', '587-555-2011', '11 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('12', 'Patron12', 'Surname12', 'patron12@example.com', '587-555-2012', '12 Example Street, Calgary, AB', '1');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('13', 'Patron13', 'Surname13', 'patron13@example.com', '587-555-2013', '13 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('14', 'Patron14', 'Surname14', 'patron14@example.com', '587-555-2014', '14 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('15', 'Patron15', 'Surname15', 'patron15@example.com', '587-555-2015', '15 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('16', 'Patron16', 'Surname16', 'patron16@example.com', '587-555-2016', '16 Example Street, Calgary, AB', '1');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('17', 'Patron17', 'Surname17', 'patron17@example.com', '587-555-2017', '17 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('18', 'Patron18', 'Surname18', 'patron18@example.com', '587-555-2018', '18 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('19', 'Patron19', 'Surname19', 'patron19@example.com', '587-555-2019', '19 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('20', 'Patron20', 'Surname20', 'patron20@example.com', '587-555-2020', '20 Example Street, Calgary, AB', '1');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('21', 'Patron21', 'Surname21', 'patron21@example.com', '587-555-2021', '21 Example Street, Calgary, AB', '0');
INSERT INTO patron (patron_id, patron_fname, patron_lname, patron_email, patron_phone, patron_address, patron_subscription) VALUES ('22', 'Patron22', 'Surname22', 'patron22@example.com', '587-555-2022', '22 Example Street, Calgary, AB', '0');
